server:
  port: 8082
  servlet:
    context-path: /market

spring:
  application:
    name: market-service
  datasource:
    url: jdbc:postgresql://localhost:15438/market_service_db
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  flyway:
    enabled: true
  threads:
    virtual:
      enabled: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jackson:
    default-property-inclusion: non_null

internal-resources:
  users-service-url: http://localhost:8081/users/
