server:
  port: 8085

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: user-service
              uri: http://localhost:8081
              predicates:
                - Path=/users/**
            - id: market-service
              uri: http://localhost:8082
              predicates:
                - Path=/market/**
    #        - id: delivery-service
    #          uri: http://localhost:8083
    #          predicates:
    #            - Path=/delivery/**