server:
  port: 8081
  servlet:
    context-path: /users

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:15438/users_service_db
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  flyway:
    enabled: true
  threads:
    virtual:
      enabled: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jackson:
    default-property-inclusion: non_null
