INSERT INTO products (title, price) VALUES
                                        ('Wireless Mouse', 29.99),
                                        ('Bluetooth Speaker', 49.95),
                                        ('Gaming Keyboard', 129.99),
                                        ('Leather Wallet', 39.50),
                                        ('Coffee Mug', 12.99),
                                        ('Desk Lamp', 34.99),
                                        ('Smartphone Stand', 19.99),
                                        ('Water Bottle', 22.50),
                                        ('Backpack', 59.99),
                                        ('Sunglasses', 89.99),
                                        ('Notebook', 8.99),
                                        ('Pen Set', 6.50),
                                        ('Headphones', 79.99),
                                        ('Portable Charger', 39.95),
                                        ('Fitness Tracker', 119.99),
                                        ('Yoga Mat', 35.50),
                                        ('Laptop Sleeve', 29.99),
                                        ('Travel Pillow', 18.99),
                                        ('Desk Organizer', 24.50),
                                        ('Wall Clock', 42.99),
                                        ('Photo Frame', 17.50),
                                        ('Candle Set', 27.99),
                                        ('Throw Blanket', 49.50),
                                        ('Table Lamp', 59.99),
                                        ('Coffee Table Book', 32.50),
                                        ('Wireless Earbuds', 99.99),
                                        ('Smartwatch', 199.99),
                                        ('Desk Chair', 149.50),
                                        ('Floor Lamp', 79.99),
                                        ('Bluetooth Headset', 49.95),
                                        ('Waterproof Backpack', 69.99),
                                        ('Laptop Stand', 34.99),
                                        ('Desk Plant', 14.50),
                                        ('Fitness Ball', 39.99);